import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/Header";
import { LocationProvider } from "./provider/LocationContext";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "600", "700", "800"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

// export const viewport: Viewport = {
//   width: "device-width",
//   initialScale: 1,
//   maximumScale: 1,
//   userScalable: false,
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

    <TooltipProvider>
      <Toaster />   
           <LocationProvider>
            <Header />
              {children}
            <Footer/>
          </LocationProvider>
    </TooltipProvider>

      </body>
    
     
  </html>
  );
}
